name: doctest-parallel-ci
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cabal:
    name: ${{ matrix.os }} / Cabal / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-24.04"]
        ghc:
          - "9.10.1"
          - "9.8.2"
          - "9.8.1"
          - "9.6.6"
          - "9.6.5"
          - "9.6.4"
          - "9.6.3"
          - "9.6.2"
          - "9.6.1"
          - "9.4.8"
          - "9.4.7"
          - "9.4.6"
          - "9.4.5"
          - "9.4.4"
          - "9.4.3"
          - "9.4.2"
          - "9.4.1"
          - "9.2.8"
          - "9.2.7"
          - "9.2.6"
          - "9.2.5"
          - "9.2.4"
          - "9.2.3"
          - "9.2.2"
          - "9.2.1"
          - "8.10.7"
          - "8.10.6"
          - "8.10.5"
          - "8.10.4"
          - "8.10.3"
          - "8.10.2"
          - "8.10.1"
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        if: matrix.ghc != 'head'
        uses: haskell-actions/setup@v2.7.5
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal: 3.12.1.0

      - name: Hello, world
        run: |
          ghc --version

